# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Configure the commit signature to come from github-actions at github-actions@github.com
      - name : Configure git username and email...
        run : git config user.name github-actions && git config user.email github-actions@github.com
        shell: bash
      # Clean install dependencies (https://docs.npmjs.com/cli/v7/commands/npm-ci)
      - name : Install dependencies...
        run : npm install
        shell: bash
      # Build the react app
      - name : Build react app...
        run : npm run build
        shell: bash
      # Bump the minor version of the react app and create a new tag
      - name : Bump minor version...
        run : npm version minor
        shell: bash
      # Add all changes from the work-tree
      - name : Add changes from the working tree...
        run : git --work-tree build add --all
        shell: bash
      # Commit all changes (automatically deploys commit with the current version number via grep)
      - name : Committ changes...
        run : git commit -m "Automatically deploying v$(npm version | grep 'site' | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+[^']*")"
        shell: bash
      # Push the changes to the gh-pages branch
      - name : Push changes to gh-pages branch...
        run : git push origin HEAD:gh-pages --force
        shell: bash
